### ISSUE TITLE
BOM Report job failure

### ISSUE THREAD

**Issue by olejens3003** [koechlm/Vault-Sample---Item-BOM-Report-Job#3]
Hi Markus
Getting now this error but only on the top level assembly, sub and part is working. I am using my own rdlc file and is working on all levels when tested. 

BOM Report job failure: System.NullReferenceException: Object reference not set to an instance of an object.
   at BOMReportJob.JobExtension.ReadBOMRow(DataTable dataTable, Dictionary`2 reportParams, BOMRow bomRow, IDictionary`2 vdfItems, PropertyValues propValues, ItemAssocProp[] assocProps, Dictionary`2 assocPropDefMap, String rowOrder, Dictionary`2 latestItemMap, Dictionary`2 fileAssocMap, Connection conn) in C:\Users\koechlm\OneDrive - autodesk\Vault Customization\Samples_MKoe\BOMReportJob-MKoe\JobExtension.cs:line 634
   at BOMReportJob.JobExtension.ReadBOMRow(DataTable dataTable, Dictionary`2 reportParams, BOMRow bomRow, IDictionary`2 vdfItems, PropertyValues propValues, ItemAssocProp[] assocProps, Dictionary`2 assocPropDefMap, String rowOrder, Dictionary`2 latestItemMap, Dictionary`2 fileAssocMap, Connection conn) in C:\Users\koechlm\OneDrive - autodesk\Vault Customization\Samples_MKoe\BOMReportJob-MKoe\JobExtension.cs:line 653
   at BOMReportJob.JobExtension.ReadBOMRow(DataTable dataTable, Dictionary`2 reportParams, BOMRow bomRow, IDictionary`2 vdfItems, PropertyValues propValues, ItemAssocProp[] assocProps, Dictionary`2 assocPropDefMap, String rowOrder, Dictionary`2 latestItemMap, Dictionary`2 fileAssocMap, Connection conn) in C:\Users\koechlm\OneDrive - autodesk\Vault Customization\Samples_MKoe\BOMReportJob-MKoe\JobExtension.cs:line 653
   at BOMReportJob.JobExtension.ReadBOMData(DataTable dataTable, Dictionary`2 reportParams, Int64 itemId, BOMType bomType, Connection conn) in C:\Users\koechlm\OneDrive - autodesk\Vault Customization\Samples_MKoe\BOMReportJob-MKoe\JobExtension.cs:line 496
   at BOMReportJob.JobExtension.GenerateBOMReport(IJob job, Connection conn) in C:\Users\koechlm\OneDrive - autodesk\Vault Customization\Samples_MKoe\BOMReportJob-MKoe\JobExtension.cs:line 110
   at BOMReportJob.JobExtension.Execute(IJobProcessorServices context, IJob job) in C:\Users\koechlm\OneDrive - autodesk\Vault Customization\Samples_MKoe\BOMReportJob-MKoe\JobExtension.cs:line 51

**Comment by koechlm** [comment]
Does the error occur using the default template on top-level assembly?

**Comment by olejens3003** [comment]
Tested and all good now. Issue was the Item Master itself and somehow W4I committed twice which created an issue in the BOMRow. After deleting the Item Master and recommit all was fine.
